Saving last configuration file to .certora_internal/24_06_03_17_53_31_630/run.conf
There is no TAC file. Going to script EVMVerifier/certoraBuild.py to main_with_args()
Creating dir /home/shan/my_project/test-audits/.certora_internal/24_06_03_17_53_31_630/.certora_config
In /home/shan/my_project/test-audits/Ownable.spec, found the imports: [('helpers/helpers.spec', '1:1'), ('methods/IOwnable.spec', '2:2')]
build failed
Failure traceback: 
CertoraUserInputError: In /home/shan/my_project/test-audits/Ownable.spec, the following import declarations do not import existing .spec files:
1:1:"/home/shan/my_project/test-audits/helpers/helpers.spec"
2:2:"/home/shan/my_project/test-audits/methods/IOwnable.spec"

Encountered an error running Certora Prover:
In /home/shan/my_project/test-audits/Ownable.spec, the following import declarations do not import existing .spec files:
1:1:"/home/shan/my_project/test-audits/helpers/helpers.spec"
2:2:"/home/shan/my_project/test-audits/methods/IOwnable.spec"

