Saving last configuration file to .certora_internal/24_05_02_18_03_51_405/run.conf
There is no TAC file. Going to script EVMVerifier/certoraBuild.py to main_with_args()
Creating dir /home/shan/my_project/test-audits/certora/contracts/.certora_internal/24_05_02_18_03_51_405/.certora_config
In /home/shan/my_project/test-audits/certora/contracts/Reentrancy.spec, found the imports: []
copying spec file /home/shan/my_project/test-audits/certora/contracts/Reentrancy.spec to /home/shan/my_project/test-audits/certora/contracts/.certora_internal/24_05_02_18_03_51_405/.certora_sources/.0_Reentrancy.spec.spec
writing /home/shan/my_project/test-audits/certora/contracts/.certora_internal/24_05_02_18_03_51_405/.certora_verify.json
Path to typechecker is /home/shan/.local/lib/python3.10/site-packages/certora_jars/Typechecker.jar
running ['java', '-jar', '/home/shan/.local/lib/python3.10/site-packages/certora_jars/Typechecker.jar', '-buildDirectory', '/home/shan/my_project/test-audits/certora/contracts/.certora_internal/24_05_02_18_03_51_405']
Failed to compile spec files:
[main] ERROR ALWAYS - Found errors in Reentrancy.spec:
[main] ERROR ALWAYS - Error in spec file (Reentrancy.spec:33:5): Syntax error: unexpected token near `assert_uint32`
build failed
Failure traceback: 
CertoraUserInputError: CVL specification syntax check failed
Encountered an error running Certora Prover:
CVL specification syntax check failed
